import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()
print("Dealing with extracting null values")
x=np.array([12,11,10,1,2,3,4,np.nan])
#When data extraction has null values nan can be used
print(np.nansum(x))
print(np.nanmax(x))
print('________________________________________________')
dataFrame=pd.read_csv("KathmanduHouse.csv")
print(dataFrame)
money=dataFrame["Price"]
kathmanduPrice=np.array(money)
print(f'The least amount of money needed to buy house in kathmandu is: {np.min(kathmanduPrice)}')
print(f'The max amount of money needed to buy house in kathmandu is: {np.max(kathmanduPrice)}')
print("--------------------------------------")
dataFrame1=pd.read_csv('LalitpurHouuse.csv')
money2=dataFrame1['price']
lalitpurPrice=np.array(money2)
print(f'The least amount of money need to buy houses in Lalitpur is {np.min(lalitpurPrice)}')
print(f'The max amount of money need to buy houses in Lalitpur is {np.max(lalitpurPrice)}')
print("--------------------------------------")
kat50=np.percentile(kathmanduPrice,50)
lat50=np.percentile(lalitpurPrice,50)
if kat50<lat50:
    print("It cheap to buy 50% of the houses in Kathmandu")
else:
    print("It cheap to buy 50% of the houses in Lalitpur")
print("--------------------------------------")
katRan=np.std(kathmanduPrice)
latRan=np.std(lalitpurPrice)
if katRan>(latRan):
    print("I will have more price choices in Kathmandu")
else:
    print("I will have more price choices in Lalitpur")
print("--------------------------------------")
kat25=np.percentile(kathmanduPrice,25)
katMax=np.max(kathmanduPrice)
kat75=np.percentile(kathmanduPrice,75)
print(f"Price range of min 25 % of the houses is {kat25} and max 25% of houses is {katMax-kat75}")
print('--------------------')
print('Null Vector')
nullVector=np.zeros(10,dtype=int)
print(nullVector)
print('---------------------')
print('Null Vector with 5th element 1')
nullVector[4]=1
print(nullVector)
print('---------------------')
print("Vector with value range from 10 to 49")
a=np.arange(10,50)
print(a)
print('---------------------')
print("Reversing vector")
print(a[::-1])
print('---------------------')
print('3x3 matrix')
print(np.arange(0,9).reshape(3,3))
print('---------------------')
print("3x3 Identity Matrix")
print(np.identity(3))
print('---------------------')
print('Finding Indices of non zero element')
myArray=np.array([1,2,0,0,4,0])
print(f'From array {myArray}')
print(np.nonzero(myArray))
print('---------------------')
print('Random array')
print(np.random.random((4,2,3)))
print('---------------------')
print("Not given case")
equalChecking = np.equal(0,myArray)
notChecking = np.not_equal(0,myArray)
print(equalChecking)
print(notChecking)
print(f'Non zero elements from above matrix is :{myArray[notChecking]}')
print('---------------------')
print("Random 10x10 vector and find max and min")
tenArray = np.random.random((10,10))
print(np.max(tenArray))
print(np.min(tenArray))
print('---------------------')
randomVector = np.random.random((30))
print(randomVector)
print(np.mean(randomVector))
print('---------------------')
print("Given 1D array, negate elements between 3 and 8")
rng = np.random.default_rng(seed = 101)
randonIntegerValue = rng.integers(0,15,(10))
print(randonIntegerValue)
toNegate = ((randonIntegerValue > 3) & (randonIntegerValue<8))
print(toNegate)
print("Result",randonIntegerValue[toNegate])
randonIntegerValue[toNegate] = randonIntegerValue[toNegate] * -1
print(randonIntegerValue)
print('---------------------')
print("Random vector of size 10 and sort it")
rng = np.random.default_rng(seed = 101)
randonIntegerValue2 = rng.integers(0,15,(10))
sortedVector = np.sort(randonIntegerValue2,kind='quicksort')
print(sortedVector)
print('---------------------')
print("Make array immutable(Read Only)")
z = np.array(np.arange(10).reshape(10))
z.flags.writeable= False
print(z)
z[0]=10
print(z)

